version: '3.8'

services:
  location.api:
    image: ${DOCKER_REGISTRY-}locationapi
    build:
      context: .
      dockerfile: Services/Location/Location.Api/Dockerfile

  usermanagement.api:
    image: ${DOCKER_REGISTRY-}usermanagementapi
    build:
      context: .
      dockerfile: Services/UserManagement/UserManagement.Api/Dockerfile

  identity.api:
    image: ${DOCKER_REGISTRY-}identityapi
    build:
      context: .
      dockerfile: Services/Identity.Api/Dockerfile

  api.gateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile

