version: '3.4'

services:
  usersregistry.db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: usersregistry.db
    environment:
      - SA_PASSWORD=DevEnvPassword123
      - ACCEPT_EULA=Y
    ports:
      - "1430:1430"

  usermanagement.api:
    build:
      context: .
      dockerfile: Services/UserManagement/UserManagement.Api/Dockerfile
      args:
        BUILD_CONFIGURATION: Debug
    container_name: usermanagement.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__SqlServer=Server=usersregistry.db;Database=UsersDb;User Id=sa;Password=DevEnvPassword123;Encrypt=False;
      - ServiceAddresses__FrontendUrl=http://localhost:8080
      - JwtSettings__SecretKey=Dev_Env_Supersecret_Very_Long_Key_2000
      - JwtSettings__Issuer=auth.api
      - JwtSettings__Audience=usermanagement
    ports:
      - "5001:8080"
    depends_on:
      - usersregistry.db

  identity.api:
    build:
      context: .
      dockerfile: Services/Identity.Api/Dockerfile
      args:
        BUILD_CONFIGURATION: Debug
    container_name: identity.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__SqlServer=Server=usersregistry.db;Database=UsersDb;User Id=sa;Password=DevEnvPassword123;Encrypt=False;
      - ServiceAddresses__FrontendUrl=http://localhost:8080
      - JwtSettings__SecretKey=Dev_Env_Supersecret_Very_Long_Key_2000
      - JwtSettings__Issuer=auth.api
      - JwtSettings__Audience=usermanagement
    ports:
      - "5002:8080"
    depends_on:
      - usersregistry.db
