version: '3.8'

services:
  usersregistry.db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: usersregistry.db
    environment:
      - SA_PASSWORD=DevEnvPassword123
      - ACCEPT_EULA=Y
    ports:
      - "1431:1430"

  location.api:
    build:
      context: Services/Location/Location.Api
      dockerfile: Dockerfile
      args:
        BUILD_CONFIGURATION: Debug
    container_name: location.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__SqlServer=Server=usersregistry.db;Database=LocationsDb;User Id=sa;Password=DevEnvPassword123;Encrypt=False;
      - ServiceAddresses__FrontendUrl=http://localhost:4200
      - JwtSettings__SecretKey=Dev_Env_Supersecret_Very_Long_Key_2000
      - JwtSettings__Issuer=auth.api
      - JwtSettings__Audience=userregistry
    ports:
      - "5000:8080"
    depends_on:
      - usersregistry.db

  usermanagement.api:
    build:
      context: Services/UserManagement/UserManagement.Api
      dockerfile: Dockerfile
      args:
        BUILD_CONFIGURATION: Debug
    container_name: usermanagement.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__SqlServer=Server=usersregistry.db;Database=UsersDb;User Id=sa;Password=DevEnvPassword123;Encrypt=False;
      - LocationClientSettings__ServiceUrl=http://location.api:8080
      - LocationClientSettings__CacheDurationInMinutes=30
      - ServiceAddresses__FrontendUrl=http://localhost:4200
      - JwtSettings__SecretKey=Dev_Env_Supersecret_Very_Long_Key_2000
      - JwtSettings__Issuer=auth.api
      - JwtSettings__Audience=userregistry
    ports:
      - "5001:8080"
    depends_on:
      - usersregistry.db

  identity.api:
    build:
      context: Services/Identity.Api
      dockerfile: Dockerfile
      args:
        BUILD_CONFIGURATION: Debug
    container_name: identity.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__SqlServer=Server=usersregistry.db;Database=UsersDb;User Id=sa;Password=DevEnvPassword123;Encrypt=False;
      - ServiceAddresses__FrontendUrl=http://localhost:4200
      - JwtSettings__SecretKey=Dev_Env_Supersecret_Very_Long_Key_2000
      - JwtSettings__Issuer=auth.api
      - JwtSettings__Audience=userregistry
    ports:
      - "5002:8080"
    depends_on:
      - usersregistry.db

  api.gateway:
    build:
      context: ApiGateway
      dockerfile: Dockerfile
      args:
        BUILD_CONFIGURATION: Debug
    container_name: api.gateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5003:8080"
    depends_on:
      - location.api
      - usermanagement.api
      - identity.api

  userregistry.web.ui:
    build:
        context: user-registry-web-ui
        dockerfile: Dockerfile
    container_name: userregistry.web.ui
    ports:
        - "4200:80"
    depends_on:
        - api.gateway
