version: '3.8'

services:
  location.api:
    image: ${DOCKER_REGISTRY-}locationapi
    build:
      context: Services/Location/Location.Api
      dockerfile: Dockerfile

  usermanagement.api:
    image: ${DOCKER_REGISTRY-}usermanagementapi
    build:
      context: Services/UserManagement/UserManagement.Api
      dockerfile: Dockerfile

  identity.api:
    image: ${DOCKER_REGISTRY-}identityapi
    build:
      context: Services/Identity.Api
      dockerfile: Dockerfile

  api.gateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: ApiGateway
      dockerfile: Dockerfile
      
  userregistry.web.ui:
    image: ${DOCKER_REGISTRY-}userregistrywebui
    build:
      context: user-registry-web-ui
      dockerfile: Dockerfile
